"""description_of_migration

Revision ID: 1de9fd4fa398
Revises: 93c3b91fd62b
Create Date: 2023-07-31 15:22:47.318865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de9fd4fa398'
down_revision = '93c3b91fd62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
