"""description_of_migration

Revision ID: 40015327947e
Revises: 094653a77926
Create Date: 2023-07-22 16:30:46.277767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40015327947e'
down_revision = '094653a77926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
