"""description_of_migration

Revision ID: f79ceb7710a5
Revises: 40015327947e
Create Date: 2023-07-22 16:32:41.868726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79ceb7710a5'
down_revision = '40015327947e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
